#!/bin/bash
#-------------------------------------------------------------------------
# Sample Slurm job script
#   for TACC Frontera CLX nodes
#
#   *** MPI Job in Normal Queue ***
# 
# Last revised: 20 May 2019
#
# Notes:
#
#   -- Launch this script by executing
#      "sbatch clx.mpi.slurm" on a Frontera login node.
#
#   -- Use ibrun to launch MPI codes on TACC systems.
#      Do NOT use mpirun or mpiexec.
#
#   -- Max recommended MPI ranks per CLX node: 56
#      (start small, increase gradually).
#
#   -- If you're running out of memory, try running
#      fewer tasks per node to give each task more memory.
#
#----------------------------------------------------

#SBATCH -J Ne4Core           # Job name
#SBATCH -o Ne4.o%j       # Name of stdout output file
#SBATCH -e Ne4.e%j       # Name of stderr error file
#SBATCH -p small          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes 
#SBATCH -n 4              # Total # of mpi tasks
#SBATCH -t 00:30:00        # Run time (hh:mm:ss)

# Any other commands must follow all #SBATCH directives...
module list
pwd
date

WDNAME="$SCRATCH/Ne4$(date +"%s")"
mkdir $WDNAME
cp -r $JOBLOC/* $WDNAME/ 
cd $SCRATCH/rmt/tests/atomic_tests 
STARTTIME=$(date +"%s")

# Launch MPI code... 
ibrun $SCRATCH/rmt/build/bin/rmt.x >> heliumTest.log         # Use ibrun instead of mpirun or mpiexec

TOTALTIME=$(expr $(date +"%s") - $STARTTIME)

NEWLINE=$'\n'
echo $"$NEWLINE --------------------$NEWLINE Run took $TOTALTIME s" >> log.out

